{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "datadog-secret",
    "namespace": "monitoring"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "datadog-secret",
        "namespace": "monitoring"
      },
      "type": "Opaque"
    },
    "encryptedData": {
      "api-key": "AgAyLwkhorUuGF9oKWpOkfalwtMpjcLvj0rDQYe5y9IJmm2uz5S9AXYGKoirgK17Y8Nd91I8QHHIV9dv4AJQZSWMBaftUaixfRmlO90zQjR5WFfS1V0Q+Crd8P+PgOgF1JLixE2IyOaqYCnj87UMw9KLAfdxVmMcmjx1iGgjLR7d1jDekqU/v2lMtz0wBMxTvZYElzCRAzn87DZuWcXaQYDoiQmGLQdkseHiuHrbnLwhwXpXLNQm4uQYhsdO9DKrQgz/3oIeKhlPzZbfHxQ/Sp5sCSGDb0ielp78PxwCyLExqP05l7PH7e1MQJIUxhrmURzaWt6Dw/mVgqdf4SadlAVsc3xZt1gEGkfdyXlXiMApREoFuJ8HBBRU+03LmK6vquviPgPD6R9m43i6nyV3iC67SiuAzA1KbBVcVH1Wq9xbWFbZ0nYViRUc41UbNNtifg+jlI06NtxyIVv3E+mlV7koRf0OZErMKxko94P8u4xoj+4d9fK2irPEhcAAWJj+n/2XjB62Wx1N0deeGhUpxqutehOad+CoQpCZBth72FNbg9VibKMR7Vc87gcEi1UcKUv7+Cjed3SciQxLs3JMFSaGjHGj0q/yYVgWgx052q2+eQVhorta/XXZfcEZPLIIjHP/HUJ2wIsRnk0aXYkw66dyRWePe0NmTfj9AJRlD5RH649n9AS+IQzpLtd8EAA+OTnWHZU2QLi9OKZqQqIC4vxo/FCXGOHkvYAlucLgCpywBA==",
      "app-key": "AgBZMHgEN1MFoba35fv9Zn4aJpWvwbCpQjHLFF8jKC+Re1Gwgfojquc3GYlm2d4A5AJitnhq7utcN2th5jG6BUC0u1Lex6XwMrZfVBJ48ESQ7h0H4UJeP9GsT0rtqH0oQty0VsMDRYFze+Wb4dtN0lTTp/1enleL0IWBDG/Uq8MuqXEhykYeH+JKtJSkRzge1qeuG9dMPJvxud6VofIm413g+ShUK5rQ01HBgi0+lbmDi63yuaEieqyKn8obGGxSAHQSDNNnsefwxdB8Dc2Bdei+yCjzLjIvY83Em+sRwZig/sX/geJ88XKQ7aUcW8jZJ2DuYaGTisxXIkUu+RpjBRqHPrDfYLlKJxgcHk7eCIDbem1PI8xtmEJrb3xKfwh2c8Gaqrt6q2jMAcAc0FI4Laja+on8xn3rsvjrxMYhDFLaPWDu7YiGgN4PdSZXHERt/vZM3yqm/3+icuqrMKxKsKnxN2pwtDev8wS6jVli3LkOuABRYLeCs2x8wPGuHFTK0kbMmMfmdMzdIo4JBxg8u2t2Hm7KLC3F/hXC1MwF6nXBUw4hZ+95EhqJp674FJrQmlbzo7ScyKarjqYe2B/Pp+yE9B9eXpSVooB/qjPe3Kdm01WjEXeY+WgbXv7DLDksGR9Yg79yTzuzROYpP1meXwkfZV5NGtSKpLO+qM9oRVmzoedkAyD0xMePOKimDvpy7HNrrAXmfsH+7VUZtlaIpUc9v03W9yyuKUqUOkhCTugoQw==",
      "token": "AgAEQHInSltMxiy0S2cKsK2PpoXwjxOVdTAFSIW+Yn6foUdb0yw1KeqA0o0GBoIa8boZhB20fts58xqc7408hhIVAh2kSyvdXHEQEXDOIzJnFakHxbtyn1mYLpucSQ3ecNukMDLsPBwwX6aIOYzKvJPJkcIf8oH5Ie1McaY6+RivgGANdKoWTk0ouOBytFrxYDQQ7fyrG6uoLrk6xNkD3VCGRf03J8j5zM85phfsW67FSET7IWYKwHVihy6uJFGVn4rv6YtWaSOYkGihv3LzrF6omiE5LGlNPhukp7zr2ypgfFy7K3ucqp5Q4xrLJPh0uSS4mJqK0e0AdwflmHZjsq0vnxluqa2qen3ERDn4fXfuosIJsyzTVKlwwq1xBq+YfFkkGOM+6aq5GFkf0GdJNZRJLqYOwALWkWQwXTq/XsKZTGYYqERh/M7HE/4IonesDyCbZXDMU6zUzwQdZqGyqWoArrYCnIgxijRCGQTf53g3bZtnOwIBSbmZlYgTtOO/njaFAJxH2Zz1XJwDqLG4jqO+No3uU4P8/pAmi8o1WSkkjwc1jjlMT7vy+rTOqRPiGWNaBYvh3a8BeEh/nqHNPWlmcb2JcYpPEyICIpoUZos1MwRG3vqpYlOXo1ba3gWjoqQLCkaaOLyUKzCnpGqL7tmJ6jI+lgUhjFKe1Z80VG1fOIzQG2KNOx/rlkol3E64Xj0E8ILFCjEmSVztvCdJ2fzB5yyAHZfCIbI92f5+OGwIow=="
    }
  }
}
