apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nvme-fast
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
parameters:
  nodePath: /mnt/k3s-system
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nvme-bulk
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
parameters:
  nodePath: /mnt/fast-scratch