repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: kustomize-validate
        name: Kustomize Validate
        entry: bash -c 'for d in $(find . -name kustomization.yaml -exec dirname {} \;); do kubectl kustomize "$d" > /dev/null; done'
        language: system
        files: kustomization\.yaml$

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: .*sealed-secret.yaml