apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: security
  namespace: argocd
spec:
  project: infrastructure
  source:
    repoURL: 'https://github.com/andre-alves5/ap108b-k3s-gitops'
    targetRevision: HEAD
    path: infrastructure/security
    kustomize:
      buildOptions: "--enable-helm"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
