apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infrastructure
  namespace: argocd
spec:
  description: "Core Cluster Services"
  sourceRepos:
    - 'https://github.com/andre-alves5/ap108b-k3s-gitops.git'
  destinations:
    - server: 'https://kubernetes.default.svc'
      namespace: kube-system
    - server: 'https://kubernetes.default.svc'
      namespace: monitoring
    - server: 'https://kubernetes.default.svc'
      namespace: kube-node-lease
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'