apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ai-processor-identity
  namespace: default
spec:
  issuerRef:
    name: homelab-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  secretName: ai-processor-tls
  commonName: "ai-processor-bot"
  duration: 24h
  renewBefore: 1h
  privateKey:
    algorithm: ECDSA
    size: 256
  usages:
    - client auth