apiVersion: apps/v1
kind: Deployment
metadata:
  name: study-buddy-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: study-buddy-frontend
  template:
    metadata:
      labels:
        app: study-buddy-frontend
    spec:
      containers:
      - name: ui
        image: {{ .Values.image }}
        envFrom:
        - configMapRef:
            name: study-buddy-config
        env:
        - name: API_URL
          value: "http://study-buddy-backend"
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
