{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "grafana-admin-credentials",
    "namespace": "monitoring"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "grafana-admin-credentials",
        "namespace": "monitoring"
      },
      "type": "Opaque"
    },
    "encryptedData": {
      "admin-password": "AgA/iY1k2g66Gx2GDV4ReEH1B/KJ2zUprytNTjx/Z8nEDYiegz9Y+M7hEFampBJsYMPC1jGWUSTqV/EhD6y/YP+XSCdMMVfJb0wDLy8iCdzyHpwbXCDB8R5eyg4OpgUjwStBBO4u1Xg57xwHMMCXk/ptaaS7nWqfRdQrKCQn34VqYXE1SIuh/UKODc1gM17e31jQBYrQ25rKgc7nRiEitouW/2w7uIX5NYX9iz6AhdWQT+WwYoydLNKGb3MYUWbvYuKqoeTBxi2HQy98rcCdAVEJP/k+7P4i14TzDUN9ywNKjtBagZc5oSx9IbUW7Z+Zsky44senZXax5YD88G92hLu88KLYX8moKIlzQHGRg0Kns39HerqpLPR1w1F69wGnUsfW2wvsl5hbne4YTl1G4MTY99wI1xGAZGK3zmf1zME1ILusPiMOjxtYdYlsjirFENPJy2pUasX+MGB7lVCtxEmhj6mSCbdX2xeNtu0glHxBXkfCYjpy2BJsfiKuPnf5IKPaHiNT2BXVrASDbuXqCg9I9TedGkiylZt+DaedTP7hTZyyCno5GvBDXuNilm6KcAw074tqBpU5vBClhZobdbxQOQg+QGALbl1KogDl5TZBDacbA/Of0iZBPeeRKmYSpd7lQm6UW/sYJXOzsaMkTNrgonWtmVkrG2PwENS03z3A9ESEAw0HIrG2sduRXk4SAPpmfmlMiUg2denQEYk=",
      "admin-user": "AgAvDCd3m51BZya/aipZmXGE5Z9L0b6t01n7JqtEz7kZXIZVh8yYnMCRzE8fHb/DfX16sTscOlkT1eLwe9HSwlkJCROIW1/iJtFZW4zidhuO3GtBw7SxtU4I71Rutl6VNiJbT9btnbzJWXmnW4wwdqVGnxGyJZAE0ziTt2bfhP8HT+z7H8HypMmeD4VtDhd6xKgpb9Ig62rSjbybnG4WUjnTxOKo6fyKEIQXbxkTJ9vGNrJ6Z6y63c2gnH/+wPpboJ7wVIDgO4KpHX9GvK8rL2/1xM0zFRz4qsnqfTD0K/J+NuWsyeJp8xxANzZ93XtrlkCsO+6wUoR4rurIjwDBOePVU5QInWnooEg5uZQTdOocdHUOh3HnoYmgyft/PMXWpMYzhuhImussDNkYjn/sK1+/UZjWkr/BRjeyN7w2ky3bzeMe78U389N5onqH4RrslnMMFzN3iiwkju2ZCntwkCsKoh5GDUxa0ZLGeYy63qwOPG9yZLIlI7T5QY95tytTbVEb8xQ/MX4vmgtALPnuH6JN28uuFqO9hFfe3/YiYHivLwthUQ/+TgUUFE5EcSXJJZFPYMnfuHfv9IA6R4norpM7Jnaol2CqpgEoUBav3OZlGLqAq371zEO/RVqeXwRW88Ni1qxM3AuEPR+XwYXDmahlMV9ZHLVAr2f5SMiNQeg2mRUYHlptMB4QG6KFgf3c5wggF5CTFg=="
    }
  }
}
