---
- name: Deploy Sealed Secrets
  hosts: all
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
    kubeconfig_path: /etc/rancher/k3s/k3s.yaml

  tasks:
    - name: Add Sealed Secrets Helm repo
      kubernetes.core.helm_repository:
        name: sealed-secrets
        repo_url: https://bitnami-labs.github.io/sealed-secrets

    - name: Install Sealed Secrets via Helm
      kubernetes.core.helm:
        release_name: sealed-secrets-controller
        chart_ref: sealed-secrets/sealed-secrets
        release_namespace: kube-system
        create_namespace: true
        chart_version: 2.16.0
        kubeconfig: "{{ kubeconfig_path }}"
        values:
          installCRDs: true
          fullnameOverride: sealed-secrets-controller
