---
- name: Deploy ArgoCD
  hosts: all
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:

    - name: Create ArgoCD namespace
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: argocd

    - name: Apply ArgoCD manifests
      kubernetes.core.k8s:
        state: present
        namespace: argocd
        src: files/argocd-install.yaml

    - name: Wait for ArgoCD pods to be ready
      ansible.builtin.pause:
        seconds: 30
