---
- name: Deploy ArgoCD
  hosts: all
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:

    - name: Create ArgoCD namespace
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: argocd

    - name: Apply ArgoCD manifests
      kubernetes.core.k8s:
        state: present
        namespace: argocd
        src: files/argocd-install.yaml

    - name: Wait for ArgoCD pods to be ready
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Pod
        namespace: argocd
      register: argocd_pods
      until: >
        (argocd_pods.resources | selectattr('status.conditions', 'defined')
        | map(attribute='status.conditions') | flatten
        | selectattr('type','equalto','Ready')
        | map(attribute='status') | list) | unique == ["True"]
      retries: 30
      delay: 10
