---
- name: Deploy ArgoCD
  hosts: all
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
    kubeconfig_path: /etc/rancher/k3s/k3s.yaml

  tasks:
    - name: Add ArgoCD Helm repo
      kubernetes.core.helm_repository:
        name: argo
        repo_url: https://argoproj.github.io/argo-helm

    - name: Install ArgoCD via Helm
      kubernetes.core.helm:
        release_name: argocd
        chart_ref: argo/argo-cd
        release_namespace: argocd
        create_namespace: true
        chart_version: 9.5.2
        kubeconfig: "{{ kubeconfig_path }}"

    - name: Enable Helm in ArgoCD Kustomize
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: patched
        kind: ConfigMap
        name: argocd-cm
        namespace: argocd
        definition:
          data:
            kustomize.buildOptions: "--enable-helm"

    - name: Wait for ArgoCD server deployment to be ready
      kubernetes.core.k8s:
        api_version: apps/v1
        kind: Deployment
        name: argocd-server
        namespace: argocd
        wait: yes
        wait_timeout: 300
        kubeconfig: "{{ kubeconfig_path }}"

    - name: Create Ingress for ArgoCD
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        definition:
          apiVersion: networking.k8s.io/v1
          kind: Ingress
          metadata:
            name: argocd-server-ingress
            namespace: argocd
            annotations:
              kubernetes.io/ingress.class: cilium
              cert-manager.io/cluster-issuer: "homelab-ca-issuer"
              ingress.cilium.io/service-type: LoadBalancer
              ingress.cilium.io/loadbalancer-mode: shared
              cilium.io/ingress.ssl-passthrough: "false"
              ingress.cilium.io/protocol: "https"
          spec:
            ingressClassName: cilium
            tls:
              - hosts:
                  - argocd.agallaghertech.online
                secretName: argocd-server-tls
            rules:
              - host: argocd.agallaghertech.online
                http:
                  paths:
                    - path: /
                      pathType: Prefix
                      backend:
                        service:
                          name: argocd-server
                          port:
                            name: https

    - name: Wait for ArgoCD TLS Certificate to be Ready
      kubernetes.core.k8s_info:
        kubeconfig: "{{ kubeconfig_path }}"
        kind: Certificate
        name: argocd-server-tls
        namespace: argocd
      register: cert_status
      until: >
        cert_status.resources | length > 0 and
        (cert_status.resources[0].status.conditions | selectattr('type', 'equalto', 'Ready') | map(attribute='status') | first == 'True')
      retries: 10
      delay: 5

    - name: Restart ArgoCD Repo Server to apply Helm config
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: patched
        kind: Deployment
        name: argocd-repo-server
        namespace: argocd
        definition:
          spec:
            template:
              metadata:
                annotations:
                  kubectl.kubernetes.io/restartedAt: "{{ ansible_date_time.iso8601 }}"
