- name: Deploy K3s environment with Cilium
  hosts: all
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
    cluster_cidr: "10.110.0.0/16"
    service_cidr: "10.43.0.0/16"
    external_cidr_start: "10.108.4.50/24"
    external_cidr_stop: "10.108.4.60/24"

  tasks:

    - name: Add Cilium Helm repo
      kubernetes.core.helm_repository:
        name: cilium
        repo_url: https://helm.cilium.io/

    - name: Install Cilium via Helm
      kubernetes.core.helm:
        release_name: cilium
        chart_ref: cilium/cilium
        release_namespace: kube-system
        create_namespace: true
        chart_version: 1.19.3
        kubeconfig: /etc/rancher/k3s/k3s.yaml
        release_values:
          operator:
            replicas: 1
          ipam:
            mode: cluster-pool
            operator:
              clusterPoolIPv4PodCIDRList: ["{{ cluster_cidr }}"]
              clusterPoolIPv4MaskSize: 24
          routingMode: tunnel
          tunnelProtocol: vxlan
          kubeProxyReplacement: "false"
          enableIPv4Masquerade: true
          enableIPv6Masquerade: false
          l2announcements:
            enabled: true
          externalIPs:
            enabled: true
          loadBalancer:
            ipPool:
              - start: "{{ external_cidr_start }}"
                stop: "{{ external_cidr_stop }}"
          hubble:
            enabled: true
            relay:
              enabled: true
            ui:
              enabled: true

    - name: Install Cilium Ingress Controller
      kubernetes.core.helm:
        release_name: cilium-ingress
        chart_ref: cilium/cilium-ingress
        release_namespace: kube-system
        create_namespace: false
        chart_version: 1.19.3
        kubeconfig: /etc/rancher/k3s/k3s.yaml
        release_values:
          loadBalancerMode: dedicated

    - name: Pause to allow Cilium pods to settle
      ansible.builtin.pause:
        seconds: 30
