# Worker-specific values
image: "andrealves5/study-buddy-worker:latest"

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"

# Secrets
secrets:
  kedaCreds: "keda-aws-creds"
